version: '3.8'

services:
  officejam:
    build: .
    ports:
      - "3003:3003"
      - "3004:3004"
    environment:
      - SERVER_PORT=3004
      - CLIENT_PORT=3003
    volumes:
      - ./queue.db:/app/queue.db